version: "3"

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    depends_on:
      - "zookeeper"
    container_name: kafka
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9090,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9090,OUTSIDE://localhost:9092
